version: "3.7"

services:
  db:
    image: postgres:13.2-alpine
    container_name: detect_db
    ports:
      - 5432:5432
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: detect_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
volumes:
  postgresql_volume:

